---
version: '3.7'

services:
  whoami:
    image: 'traefik/whoami'
    environment:
        TZ: 'Europe/Paris'
    logging:
      options:
        tag: 'whoami'
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.whoami.rule=Host(`whoami.127.0.0.1.nip.io`)"
      - "traefik.http.routers.whoami.entrypoints=web"
      - "traefik.http.routers.whoami.priority=100"
      - "traefik.http.services.whoami.loadbalancer.sticky.cookie=false"
      # - "traefik.http.services.whoami.loadbalancer.sticky.cookie=true"
      # - "traefik.http.services.whoami.loadbalancer.sticky.cookie.name=whoami_sticky_session"
      - "traefik.http.services.whoami.loadbalancer.server.port=80"
      - "traefik.http.services.whoami.loadbalancer.server.scheme=http"
      - "traefik.http.services.whoami.loadbalancer.healthcheck.interval=15s"
      - "traefik.http.services.whoami.loadbalancer.healthcheck.timeout=5s"
      - "traefik.http.services.whoami.loadbalancer.healthcheck.path=/"
      - "traefik.http.services.whoami.loadbalancer.healthcheck.followRedirects=false"
