---
version: '3.7'

services:
  maintenance-banner:
    build:
      context: './maintenance-banner'
    environment:
        TZ: 'Europe/Paris'
    logging:
      options:
        tag: 'maintenance-banner'
    labels:
      - "traefik.enable=true"
      - "traefik.http.middlewares.maintenance-banner-retry.retry.attempts=10"
      - "traefik.http.middlewares.maintenance-banner-retry.retry.initialinterval=100ms"
      - "traefik.http.routers.whoami-maintenance-banner.rule=Host(`whoami.127.0.0.1.nip.io`) && !HeadersRegexp(`User-Agent`, `nobanner`)"
      - "traefik.http.routers.whoami-maintenance-banner.priority=101"
      - "traefik.http.routers.whoami-maintenance-banner.entrypoints=web"
      - "traefik.http.routers.whoami-maintenance-banner.middlewares=maintenance-banner-retry@docker"
      - "traefik.http.services.whoami-maintenance-banner.loadbalancer.sticky.cookie=false"
      - "traefik.http.services.whoami-maintenance-banner.loadbalancer.server.port=80"
      - "traefik.http.services.whoami-maintenance-banner.loadbalancer.server.scheme=http"
      - "traefik.http.services.whoami-maintenance-banner.loadbalancer.healthcheck.interval=5s"
      - "traefik.http.services.whoami-maintenance-banner.loadbalancer.healthcheck.timeout=2s"
      - "traefik.http.services.whoami-maintenance-banner.loadbalancer.healthcheck.path=/"
      - "traefik.http.services.whoami-maintenance-banner.loadbalancer.healthcheck.followRedirects=false"
      #- "traefik.http.services.whoami-maintenance-banner.loadbalancer.serverstransport=shortForwardingTimeouts@file"
